# Generated by Django 2.2.8 on 2020-09-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200911_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
