# Generated by Django 2.2.8 on 2020-09-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
    ]
