# Generated by Django 2.2.8 on 2020-09-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('Notice', 'Notice'), ('English', 'English'), ('French', 'French'), ('Korean', 'Korean')], max_length=30, null=True),
        ),
    ]
