# Generated by Django 2.2.8 on 2020-09-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_slug_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modifyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
